# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ethos"
description = "Ethos Technologies Theme"
license = "MIT"
licenselink = "https://github.com/ethostech/ethos-hugo-theme/blob/master/LICENSE.md"
homepage = "https://ethos.tech"
tags = ["blog", "company"]
features = ["", "", ""]
min_version = 0.40

[author]
  name = "Ethos Technologies"
  homepage = "https://ethos.tech"
